## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('simple-hd-olsr',
                                 ['internet', 'hd-olsr', 'propagation', 'applications', 'wifi', 'mobility'])
    obj.source = 'simple-hd-olsr.cc'
